In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
import numpy as np
b = np.array(((1,2,3),(4,5,6),(7,8,9)))
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
import numpy as np
c = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
import numpy as np
b = np.array(a,float)
print(b)

[1. 2. 3.]


In [12]:
import numpy as np
c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [13]:
import numpy as np
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
import numpy as np
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.size)
print(b.size)

3
9


In [16]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.shape)
print(b.size)

(3,)
9


In [17]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.size)
print(b.shape)

3
(3, 3)


In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.size)
print(b.T)

3
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.size)
print(b.sum())

3
45


In [20]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.size)
print(b.mean())

3
5.0


In [21]:
import numpy as np
a=np.array([1,2,3])
b=np.array(([1,2,3],[4,5,6],[7,8,9]))
print(a.size)
print(b.var())

3
6.666666666666667


In [26]:
#reshape
import numpy as np
a=np.array([1,0,0,1,3,4,5,6,0,7,4,6,0,0,2]).reshape(3,5)
print(a)


[[1 0 0 1 3]
 [4 5 6 0 7]
 [4 6 0 0 2]]


In [30]:
#arange
import numpy as np
a=np.arange(1,100,20)
print(a)

[ 1 21 41 61 81]


In [32]:
#Linespace
import numpy as np
a=np.linspace(0,100,30)
print(a)

[  0.           3.44827586   6.89655172  10.34482759  13.79310345
  17.24137931  20.68965517  24.13793103  27.5862069   31.03448276
  34.48275862  37.93103448  41.37931034  44.82758621  48.27586207
  51.72413793  55.17241379  58.62068966  62.06896552  65.51724138
  68.96551724  72.4137931   75.86206897  79.31034483  82.75862069
  86.20689655  89.65517241  93.10344828  96.55172414 100.        ]


In [35]:
#random
import numpy as np
np.random.random(10)


array([0.18418578, 0.66451936, 0.05974985, 0.60791417, 0.64914091,
       0.07462663, 0.87499919, 0.33069737, 0.99843353, 0.01016815])

In [37]:
import numpy as np
np.random.randint(0,100,10)

array([12, 92, 72, 83, 98, 13, 21, 23, 15, 98])

In [38]:
#slicing
import numpy as np
x=np.arange(24).reshape(4,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [39]:
#slicing
import numpy as np
x=np.arange(24).reshape(4,6)
print(x[1:])#from row X to Y-1

[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [40]:
#slicing
import numpy as np
x=np.arange(24).reshape(4,6)
print(x[:,2:4])#from cloumn a to b-1(all rows)

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]


In [47]:
#read data
import numpy as np
my_data= np.genfromtxt('GSS1993_UnhappyFinal.csv', delimiter=',',dtype=None,encoding=None)
print(my_data)


[['UNHAPPY' 'AGE' 'HEALTH' ... 'NEVER_MARRIED' 'BLACK' 'OTHER_RACE']
 ['1' '43.0' '2' ... '0' '0' '0']
 ['0' '44.0' '3' ... '1' '1' '0']
 ...
 ['0' '35.0' '3' ... '0' '0' '0']
 ['0' '25.0' '4' ... '0' '0' '0']
 ['0' '30.0' '3' ... '0' '0' '0']]


In [43]:
import numpy as np

x=np.arange(24).reshape(4,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [46]:
import numpy as np
import pandas as pd
x=np.arange(24).reshape(4,6)
pd.DataFrame(x)

0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23